#!/usr/bin/env python3
"""Tests for compliance artifact generation and file system operations."""

import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../platform"))

from apparat.horizontal_texture_processor import HorizontalTextureProcessor
from apparat.phase_handlers import compliance_baseline_handler


def test_compliance_artifact_generation():
    """Test that compliance handler generates all required artifacts."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        # Verify all three files were created
        license_path = Path(temp_dir) / "LICENSE"
        notice_path = Path(temp_dir) / "NOTICE"
        terms_path = Path(temp_dir) / "TERMS_OF_ENGAGEMENT.md"

        assert license_path.exists(), "LICENSE file should be created"
        assert notice_path.exists(), "NOTICE file should be created"
        assert terms_path.exists(), "TERMS_OF_ENGAGEMENT.md should be created"

        print("PASS: test_compliance_artifact_generation")


def test_license_file_content():
    """Test that LICENSE file contains required Apache 2.0 elements."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        license_path = Path(temp_dir) / "LICENSE"
        license_content = license_path.read_text(encoding="utf-8")

        # Check for required Apache 2.0 elements
        assert "Apache License" in license_content
        assert "Version 2.0" in license_content
        assert "http://www.apache.org/licenses/" in license_content
        assert "Irfan Kabir" in license_content
        assert "Licensed under the Apache License" in license_content

        print("PASS: test_license_file_content")


def test_notice_file_content():
    """Test that NOTICE file contains required attribution information."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        notice_path = Path(temp_dir) / "NOTICE"
        notice_content = notice_path.read_text(encoding="utf-8")

        # Check for required notice elements
        assert "Mangrove — Compliance Notice" in notice_content
        assert "Irfan Kabir" in notice_content
        assert "Mangrove ecosystem contributors" in notice_content
        assert "Apache License" in notice_content

        print("PASS: test_notice_file_content")


def test_terms_of_engagement_structure():
    """Test that TERMS_OF_ENGAGEMENT.md has the correct structure."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        terms_path = Path(temp_dir) / "TERMS_OF_ENGAGEMENT.md"
        terms_content = terms_path.read_text(encoding="utf-8")

        # Check for required sections
        assert "Terms of Engagement" in terms_content
        assert "Generated by Apparat phase" in terms_content
        assert "Authority documents" in terms_content
        assert "Hard baseline" in terms_content
        assert "Governance & safety" in terms_content

        print("PASS: test_terms_of_engagement_structure")


def test_compliance_artifact_recording():
    """Test that compliance artifacts are recorded in processor state."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        # Check that artifacts were recorded
        assert processor.ipo.compliance_artifacts is not None
        assert len(processor.ipo.compliance_artifacts) == 3

        # Check artifact structure (path, digest, size)
        for artifact in processor.ipo.compliance_artifacts:
            assert len(artifact) == 3
            path, digest, size = artifact
            assert isinstance(path, Path)
            assert isinstance(digest, str)
            assert digest.startswith("sha256:")
            assert isinstance(size, int)
            assert size > 0

        print("PASS: test_compliance_artifact_recording")


def test_compliance_idempotency():
    """Test that re-running compliance handler doesn't overwrite existing files."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        # First run
        compliance_baseline_handler(processor, {})
        license_path = Path(temp_dir) / "LICENSE"
        original_content = license_path.read_text(encoding="utf-8")
        original_mtime = license_path.stat().st_mtime

        # Second run
        compliance_baseline_handler(processor, {})
        new_content = license_path.read_text(encoding="utf-8")
        new_mtime = license_path.stat().st_mtime

        # Content should be identical (file not overwritten)
        assert original_content == new_content
        # Modification time should be the same (file not touched)
        assert original_mtime == new_mtime

        print("PASS: test_compliance_idempotency")


def test_compliance_with_custom_root():
    """Test compliance handler with custom root directory."""
    with tempfile.TemporaryDirectory() as temp_dir:
        custom_root = Path(temp_dir) / "custom_compliance"
        custom_root.mkdir()

        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = str(custom_root)
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        # Files should be in custom directory
        assert (custom_root / "LICENSE").exists()
        assert (custom_root / "NOTICE").exists()
        assert (custom_root / "TERMS_OF_ENGAGEMENT.md").exists()

        print("PASS: test_compliance_with_custom_root")


def test_compliance_preserves_input_data():
    """Test that compliance handler preserves input data."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir

        # Set some input data
        from apparat.api import GridCell
        processor.ipo.input_data = [
            GridCell(0, 0, 1.0, "test"),
            GridCell(1, 0, 2.0, "test"),
        ]

        result = compliance_baseline_handler(processor, {})

        # Input data should be preserved
        assert result == processor.ipo.input_data
        assert len(result) == 2
        assert result[0].value == 1.0
        assert result[1].value == 2.0

        print("PASS: test_compliance_preserves_input_data")


def test_compliance_digest_format():
    """Test that file digests are in the correct format."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        # Check digest format
        for artifact in processor.ipo.compliance_artifacts:
            path, digest, size = artifact
            assert digest.startswith("sha256:")
            # Should be 16 hex characters after "sha256:"
            assert len(digest) == len("sha256:") + 16
            # All characters after prefix should be hex
            hex_part = digest[len("sha256:") :]
            assert all(c in "0123456789abcdef" for c in hex_part)

        print("PASS: test_compliance_digest_format")


def test_compliance_file_sizes():
    """Test that generated files have reasonable sizes."""
    with tempfile.TemporaryDirectory() as temp_dir:
        processor = HorizontalTextureProcessor(4, 4)
        processor.ipo.compliance_root = temp_dir
        processor.ipo.input_data = []

        compliance_baseline_handler(processor, {})

        # Check file sizes
        license_path = Path(temp_dir) / "LICENSE"
        notice_path = Path(temp_dir) / "NOTICE"
        terms_path = Path(temp_dir) / "TERMS_OF_ENGAGEMENT.md"

        # All files should have content
        assert license_path.stat().st_size > 100
        assert notice_path.stat().st_size > 100
        assert terms_path.stat().st_size > 500  # Terms file is longer

        print("PASS: test_compliance_file_sizes")


if __name__ == "__main__":
    test_compliance_artifact_generation()
    test_license_file_content()
    test_notice_file_content()
    test_terms_of_engagement_structure()
    test_compliance_artifact_recording()
    test_compliance_idempotency()
    test_compliance_with_custom_root()
    test_compliance_preserves_input_data()
    test_compliance_digest_format()
    test_compliance_file_sizes()
    print("\n✨ All compliance tests passed!")
