"""
Phase Handlers for Horizontal Texture Processor.
This module implements the core processing logic for each phase,
adhering to the high-accuracy foundational API.
"""

import datetime
import hashlib
from pathlib import Path

from .api import GridCell, IProcessor, PhaseParams


def compliance_baseline_handler(processor: IProcessor, params: PhaseParams) -> list[GridCell]:
    """Generate the compliance-baseline artefacts at the apparat root."""
    root: Path = (
        Path(processor.ipo.compliance_root)
        if processor.ipo.compliance_root
        else Path(__file__).resolve().parent.parent.parent
    )

    artefacts: list[tuple[Path, str, int]] = []

    license_text = (
        "MIT License\n"
        "\n"
        "Copyright (c) 2024-2026 Irfan Kabir\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
    )
    license_path = root / "LICENSE"
    if not license_path.exists():
        license_path.write_text(license_text, encoding="utf-8")
    artefacts.append(
        (
            license_path,
            _digest(license_path.read_text(encoding="utf-8")),
            license_path.stat().st_size,
        )
    )

    notice_text = (
        "Mangrove — Compliance Notice\n"
        "============================\n"
        "\n"
        "This product includes software developed by:\n"
        "\n"
        "  • Irfan Kabir — primary author.\n"
        "  • The Mangrove ecosystem contributors — see git log for the\n"
        "    authoritative author list per file.\n"
        "\\ la\n"
        "Project layout\n"
        "--------------\n"
        "  Live tree  : /home/cable/series/mangrove/        (stub, this repo)\n"
        "  Canonical  : /home/irfankabir/                   (538 GB volume,\n"
        "                                                   UUID cf656878-be07-4249-b8ba-10fd482aa610,\n"
        "                                                   currently unmounted\n"
        "                                                   from this session)\n"
        "\n"
        "Build / runtime\n"
        "--------------\n"
        "  Python interpreter : /home/cable/local/bin/python3.13\n"
        "                       (CPython 3.13.14, user-space build)\n"
        "  License of build   : PSF License — see /home/cable/local/lib/python3.13/LICENSE.txt\n"
        "\n"
        "Licensed under the MIT License. See LICENSE in this directory\n"
        "for the full text.\n"
    )
    notice_path = root / "NOTICE"
    if not notice_path.exists():
        notice_path.write_text(notice_text, encoding="utf-8")
    artefacts.append(
        (notice_path, _digest(notice_path.read_text(encoding="utf-8")), notice_path.stat().st_size)
    )

    terms_text = (
        "# Terms of Engagement — Mangrove Series\n"
        "\n"
        "_Generated by Apparat phase `compliance_baseline`._\n"
        "_Generated on: "
        + datetime.datetime.now(datetime.UTC).isoformat(timespec="seconds")
        + "_\n"
        "\n"
        "This document consolidates the operator-stated terms that govern work\n"
        "performed on this workspace. It is generated from the live sources, not\n"
        "authored from intent.\n"
        "\n"
        "## 1. Authority documents (in order of precedence)\n"
        "\n"
        "1. `~/WORKFLOW.md` — binding; wins on conflict with anything below.\n"
        "2. `series/CLAUDE.md` — ecosystem map, build order, data contracts.\n"
        "3. The closest `CLAUDE.md` / `AGENTS.md` / `GEMINI.md` to the file being edited.\n"
        "4. `~/docs/PROJECT_REGISTRY.yaml` — canonical project registry.\n"
        "5. `~/.claude/projects/-home-cable-series/memory/MEMORY.md` — operator-curated\n"
        "   auto-memory, persists across sessions.\n"
        "\n"
        "Note: `README.md` historically references `docs/CLAUDE.md` as authoritative;\n"
        "that file does not exist. `mangrove/CLAUDE.md` is canonical in its place.\n"
        "\n"
        "## 2. Live vs canonical surface\n"
        "\n"
        "The live working tree at `/home/cable/series/mangrove/` is a **stub**.\n"
        "Its `finance/`, `intelligence/`, `operations/`, `productivity/`, `lab/`,\n"
        "`workspace/`, `routines/`, `scripts/`, `platform/` directories are empty\n"
        "of code. The canonical archive lives on the 538 GB volume at\n"
        "`/home/irfankabir/` (volume UUID `cf656878-be07-4249-b8ba-10fd482aa610`),\n"
        "containing 60+ packages and 34 lab packages under\n"
        "`domains/platform/operations/lab/`. The volume is **not mounted** by\n"
        "default in this session. Verify any path before relying on it.\n"
        "\n"
        "## 3. Hard baseline (survives context compression)\n"
        "\n"
        "- Read before write — never edit a file you haven't read this session.\n"
        "- `uv run` for all Python. Never bare `pip` or `python`.\n"
        "- No `--no-verify`, no `sudo` from agent, no history rewrite without\n"
        "  operator consent.\n"
        "- Conventional commits with scope. Stage explicit paths only — never\n"
        "  `git add -A` / `git add .`.\n"
        "- Identity via `~/.gitconfig` `includeIf` — `caraxesthebloodwyrm02`\n"
        "  (primary/CascadeProjects), `irfankabir02` (secondary/grove). The npm\n"
        "  scope is `@irfankabir002` (trailing `2` before the slash). Never set\n"
        "  `user.name`/`user.email` ad hoc.\n"
        "\n"
        "## 4. Governance & safety\n"
        "\n"
        "- **Trust Contract (TUV-001):** canonical rules live at\n"
        "  `/home/irfankabir/docs/AGENTS.md` on the canonical archive. The legacy\n"
        "  reference `/mnt/arch_data/.../development-contract.md` is on the\n"
        "  unmounted Arch partition and may not resolve on this host.\n"
        "- **3PAA-SHADOW Containment:** Hard Deny `factory.ai`, `cursor.com`,\n"
        "  `cursor.sh`, `workos.com`. Blocked ports: 54621, 8081, 40925. Port\n"
        "  8788 is blocked for all uses **except** x-change production.\n"
        "- **Privileges:** no `sudo` from agent. Collect privileged steps for\n"
        "  operator execution.\n"
        "- **Pseudonym homes:** the five UIDs on the volume (bumblebee, cable,\n"
        "  gridstral, pheonix, irfankabir) are separate UIDs, **not** aliases.\n"
        "  Content is per-user and access-controlled. Only `irfankabir/` is\n"
        "  fully readable without chmod escalation.\n"
        "- **`python-craft`** (author `shinychoes`) is collaborator-owned — out\n"
        "  of audit-edit scope.\n"
        "\n"
        "## 5. In-force memory entries (session scope)\n"
        "\n"
        "These are the operator-curated memories that govern session behaviour,\n"
        "as listed in `~/.claude/projects/-home-cable-series/memory/MEMORY.md`:\n"
        "\n"
        '1. **user-identity** — Irfan Kabir / "Prince"; live as `cable` on\n'
        "   Fedora 43; canonical home `/home/irfankabir/` on the 538 GB volume.\n"
        "2. **pseudonym-directory-convention** — five homes on the volume are\n"
        "   separate UIDs, not aliases; access-controlled.\n"
        "3. **apparat-overview** — what Apparat is: dynamic phase-handler\n"
        "   registry for `horizontal_texture_processor.py`; creative project by\n"
        "   the user, credited to apparat-joel.\n"
        "4. **apparat-conventions** — string keys, intentional `Any` annotations,\n"
        "   registry-lookup refactor pattern, built-in handler defaults.\n"
        "5. **golding-monorepo** — slice contract (4,16,64), baseline\n"
        "   normalizer, run modes — Apparat-bounding constraints only.\n"
        "6. **reference-history-volume** — pointer to the 538 GB volume mount\n"
        "   path and current access state.\n"
        "7. **feedback-permission-tuning** — user runs `/permissions`\n"
        "   interactively; ask before escalating filesystem permission scopes.\n"
        "8. **feedback-conversation-vs-action-mode** — after tool calls, shift\n"
        "   to plain chat; no file-path dumps, byte counts, or decision tables\n"
        "   unless asked.\n"
        "9. **irfankabir-canonical-workspace** — full canonical surface on the\n"
        "   volume: domains/platform/, school/, workspace/, lab/ (34 packages),\n"
        "   routines/; live `/home/cable/series/mangrove/` tree is a stub;\n"
        "   author/license matrix.\n"
        "10. **sisa-trigger** — typing `sisa` in a prompt bootstraps the Apparat\n"
        "   workflow (`platform/apparat/sisa.py`); load phases, check prereqs,\n"
        "   surface warnings, then ask via AskUserQuestion.\n"
        "\n"
        "## 6. Toolchain constraints\n"
        "\n"
        "- Python 3.13+ — interpreter lives at `/home/cable/local/bin/python3.13`\n"
        "  (user-space build; lacks `_ssl`, `_ctypes`, `_sqlite3` modules by\n"
        "  deliberate operator decision). `uv` is the canonical dependency\n"
        "  manager.\n"
        "- Node: `npm` for most projects; `pnpm` only for `mcp-tool-experiment`.\n"
        "- OS packages: `apt` only. No `sudo` from agent — collect privileged steps for\n"
        "  operator execution.\n"
        "- Conventional commits with scope. Stage explicit paths only.\n"
        "\n"
        "## 7. Decision posture (session-current)\n"
        "\n"
        '- "Accept user-space as final" — interpreter installs to\n'
        "  `/home/cable/local/`. No `/usr/local` install attempted without\n"
        "  explicit operator reopening.\n"
        "- Staging deferred — no commits produced without explicit operator\n"
        "  approval.\n"
        "\n"
        "## 8. Provenance\n"
        "\n"
        "This document was generated by the Apparat `compliance_baseline` phase.\n"
        "Re-running the phase regenerates the file; diff against the prior\n"
        "version to surface drift.\n"
    )
    terms_path = root / "TERMS_OF_ENGAGEMENT.md"
    if not terms_path.exists():
        terms_path.write_text(terms_text, encoding="utf-8")
    artefacts.append(
        (terms_path, _digest(terms_path.read_text(encoding="utf-8")), terms_path.stat().st_size)
    )

    processor.ipo.compliance_artifacts = artefacts  # type: ignore[attr-defined]
    return processor.ipo.input_data


def _digest(text: str) -> str:
    return "sha256:" + hashlib.sha256(text.encode()).hexdigest()[:16]


def initiate_handler(processor: IProcessor, params: PhaseParams) -> list[GridCell]:
    """Initiate processing: create an empty grid based on resolution."""
    cells = []
    for y in range(processor.resolution[1]):
        for x in range(processor.resolution[0]):
            cell = GridCell(x, y, 0.0, "empty")
            cells.append(cell)
    processor.ipo.input_data = cells
    return cells


def quantize_handler(processor: IProcessor, params: PhaseParams) -> list[GridCell]:
    """Quantize grid cell values to 1 decimal place."""
    if not processor.ipo.input_data:
        return []
    quantized = [
        GridCell(cell.x, cell.y, round(cell.value * 10) / 10, cell.texture_type)
        for cell in processor.ipo.input_data
    ]
    processor.ipo.input_data = quantized
    return quantized


def combine_handler(processor: IProcessor, params: PhaseParams) -> list[GridCell]:
    """Combine texture patterns using the repetition generator."""
    combinations = processor.generator.generate(2)
    if not processor.ipo.input_data:
        return []
    combined = []
    for i, cell in enumerate(processor.ipo.input_data):
        pattern_idx = i % len(combinations)
        texture = "-".join(combinations[pattern_idx])
        combined.append(GridCell(cell.x, cell.y, cell.value, texture))
    processor.ipo.input_data = combined
    return combined


def render_handler(processor: IProcessor, params: PhaseParams) -> list[GridCell]:
    """Render spatial output via the ComputationalQuantizationMatrix."""
    from .api import SpatialRender

    SpatialRender(processor.matrix)
    return processor.ipo.processed_data or processor.ipo.input_data


def complete_handler(processor: IProcessor, params: PhaseParams) -> list[GridCell]:
    """Complete phase: final read of current data."""
    return processor.ipo.input_data
